apiVersion: apps/v1
kind: Deployment
metadata:
  name: survival-predictor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: survival-predictor
  template:
    metadata:
      labels:
        app: survival-predictor
    spec:
      containers:
        - name: survival-predictor
          image: sahithaitha02/home-assignment-survivalprediction:latest
          command: ["python", "-m", "uvicorn", "scripts.api.app:app", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - containerPort: 8000
